<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zach Ginder">

<title>EDA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-79108a0fc1995748cbd19a5b0e3e3e7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">EDA</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zach Ginder </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The data explored in this analysis comes from the the CDC’s BRFSS2015 survey. The target variable for analysis is the Diabetes_binary variable which is in 2 classes: no diabetes or prediabetes/diabetes. There are 21 predictor variables in the dataset to potentially include in the subsequent models.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 66%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th>Description</th>
<th>Classes or Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HighBP</td>
<td>Factor variable for high blood pressure</td>
<td>“No High BP” or “High BP”</td>
</tr>
<tr class="even">
<td>HighChol</td>
<td>Factor variable for high cholesterol</td>
<td>“No High Cholesterol” or “High Cholesterol”</td>
</tr>
<tr class="odd">
<td>CholCheck</td>
<td>Factor variable for if the respondent received a cholesterol check in the last 5 years</td>
<td>“No Cholesterol Check In 5 Years” or “Yes Cholesterol Check In 5 Years”</td>
</tr>
<tr class="even">
<td>BMI</td>
<td>Continuous variable for the body mass index of the respondent</td>
<td>Values greater than 0</td>
</tr>
<tr class="odd">
<td>Smoker</td>
<td>Factor variable where a smoker means the respondent has smoked at least 100 cigarettes (5 packs) in their entire lifetime.</td>
<td>“Smoker” or “Not A Smoker”</td>
</tr>
<tr class="even">
<td>Stroke</td>
<td>Factor variable for whether the respondent has been diagnosed with a stroke or not.</td>
<td>“Diagnosed With Stroke” or “No Stroke”</td>
</tr>
<tr class="odd">
<td>HeartDiseaseorAttack</td>
<td>Factor variable for whether the respondent has been diagnosed with heart disease and/or myocardial infarction or not.</td>
<td>“Coronary Heart Disease or Myocardial Infarction” or “No Heart Disease Evident”</td>
</tr>
<tr class="even">
<td>PhysActivity</td>
<td>Factor variable for whether the respondent was physically active in the past 30 days or not (not including job).</td>
<td>“Physical Activity in Past 30 Days” or “No Physical Activity in Past 30 Days”</td>
</tr>
<tr class="odd">
<td>Fruits</td>
<td>Factor variable on whether the respondent consumes fruit regularly, defined as consuming fruit 1 or more times per day.</td>
<td>“Consume Fruit 1 Or More Times Per Day” or “Does Not Consume Fruits Regularly”</td>
</tr>
<tr class="even">
<td>Veggies</td>
<td>Factor variable on whether the respondent consumes vegetables regularly, defined as consuming vegetables 1 or more times per day.</td>
<td>“Consume Vegetables 1 Or More Times Per Day” or “Does Not Consume Vegetables Regularly”</td>
</tr>
<tr class="odd">
<td>HvyAlcoholConsump</td>
<td>Factor variable on whether the respondent is a heavy alcohol consumer or not. This is defined as heavy if the respondent is an adult men and drinks 14 or more drinks per week or 7 or more drinks per week for adult women.</td>
<td>“Heavy Alcohol Consumer” or “Not Heavy Alcohol Consumer”</td>
</tr>
<tr class="even">
<td>AnyHealthcare</td>
<td>Factor variable for whether the respondent has any kind of health care coverage, including health insurance, prepaid plans such as HMO, etc.</td>
<td>“Has Health Insurance” or “No Health Insurance”</td>
</tr>
<tr class="odd">
<td>NoDocbcCost</td>
<td>Factor variable for whether the respondent in the past 12 months could not see a doctor due to cost but needed to.</td>
<td>“Missed Doctors Visit Due to Cost” or “No Cost Barrier to Healthcare”</td>
</tr>
<tr class="even">
<td>GenHlth</td>
<td>Factor variable for the respondents general health.</td>
<td><p>“Excellent”</p>
<p>“Very Good”</p>
<p>“Good”</p>
<p>“Fair”</p>
<p>“Poor”</p></td>
</tr>
<tr class="odd">
<td>MentHlth</td>
<td>Count variable for the number of days of poor mental health in the last 30 days.</td>
<td>Scale from 1 to 30</td>
</tr>
<tr class="even">
<td>PhysHlth</td>
<td>Count variable for the number of days of physical illness or injury in the last 30 days.</td>
<td>Scale from 1 to 30</td>
</tr>
<tr class="odd">
<td>DiffWalk</td>
<td>Factor variable for whether the respondent had difficulty with walking or climbing stairs.</td>
<td>“Difficulty With Walking or Stairs” or “No Difficulty With Walking or Stairs”</td>
</tr>
<tr class="even">
<td>Sex</td>
<td>Factor variable for the respondents sex.</td>
<td>“Female” or “Male”</td>
</tr>
<tr class="odd">
<td>Age</td>
<td>Factor variable for the respondents age.</td>
<td><p>“18-24”</p>
<p>“25-29”</p>
<p>“30-34”</p>
<p>“35-39”</p>
<p>“40-44”</p>
<p>“45-49”</p>
<p>“50-54”</p>
<p>“55-59”</p>
<p>“60-64”</p>
<p>“65-69”</p>
<p>“70-74”</p>
<p>“75-79”</p>
<p>“80 or older”</p></td>
</tr>
<tr class="even">
<td>Education</td>
<td>Factor variable for the respondents highest completed education.</td>
<td><p>“Never Attended School Or Only Kindergarten”</p>
<p>“Grades 1-8”</p>
<p>“Grades 9-11”</p>
<p>“Grades 12 or GED”</p>
<p>“Some College or Technical School”</p>
<p>“Graduated College or Technical School”</p></td>
</tr>
<tr class="odd">
<td>Income</td>
<td>Factor variable for the respondents income.</td>
<td><p>“Less than $10,000”</p>
<p>“$10,000 to less than $15,000”</p>
<p>“$15,000 to less than $20,000”</p>
<p>“$20,000 to less than $25,000”</p>
<p>“$25,000 to less than $35,000”</p>
<p>“$35,000 to less than $50,000”</p>
<p>“$50,000 to less than $75,000”</p>
<p>“$75,000 or more”</p></td>
</tr>
</tbody>
</table>
<p>The dataset is unbalanced meaning there are more cases where the survey respondent had no diabetes than in the case where the survey respondent either had prediabetes or diabetes. This is important when it comes to modeling as we likely will want to ensure that our model does better than the majority class rate, or rate of the largest class of the dataset, in this case being the no diabetes class. If a model only predicted the majority class it would still achieve this majority class accuracy, but it would not be useful. Ensuring the model is useful in predicting the Diabetes_binary variable based on a set of predictors is the goal and ensuring the accuracy of the model is better than the majority class rate will be one important evaluation of model importance. This exploratory data analysis serves to try to determine a few useful predictors to use when</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Library these packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Read in csv file</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Diabetes<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"diabetes_binary_health_indicators_BRFSS2015.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Determine structure of data</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   253680 obs. of  22 variables:
 $ Diabetes_binary     : num  0 0 0 0 0 0 0 0 1 0 ...
 $ HighBP              : num  1 0 1 1 1 1 1 1 1 0 ...
 $ HighChol            : num  1 0 1 0 1 1 0 1 1 0 ...
 $ CholCheck           : num  1 0 1 1 1 1 1 1 1 1 ...
 $ BMI                 : num  40 25 28 27 24 25 30 25 30 24 ...
 $ Smoker              : num  1 1 0 0 0 1 1 1 1 0 ...
 $ Stroke              : num  0 0 0 0 0 0 0 0 0 0 ...
 $ HeartDiseaseorAttack: num  0 0 0 0 0 0 0 0 1 0 ...
 $ PhysActivity        : num  0 1 0 1 1 1 0 1 0 0 ...
 $ Fruits              : num  0 0 1 1 1 1 0 0 1 0 ...
 $ Veggies             : num  1 0 0 1 1 1 0 1 1 1 ...
 $ HvyAlcoholConsump   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ AnyHealthcare       : num  1 0 1 1 1 1 1 1 1 1 ...
 $ NoDocbcCost         : num  0 1 1 0 0 0 0 0 0 0 ...
 $ GenHlth             : num  5 3 5 2 2 2 3 3 5 2 ...
 $ MentHlth            : num  18 0 30 0 3 0 0 0 30 0 ...
 $ PhysHlth            : num  15 0 30 0 0 2 14 0 30 0 ...
 $ DiffWalk            : num  1 0 1 0 0 0 0 1 1 0 ...
 $ Sex                 : num  0 0 0 0 0 1 0 0 0 1 ...
 $ Age                 : num  9 7 9 11 11 10 9 11 9 8 ...
 $ Education           : num  4 6 4 3 5 6 6 4 5 4 ...
 $ Income              : num  3 1 8 6 4 8 7 4 1 3 ...</code></pre>
</div>
</div>
<p>The data for this analysis can be found at the following website (<a href="https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset/" class="uri">https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset/</a>). As noticed above, all the variables are treated as numeric; however, a majority of the variables are actually factors. We can transform those variables into factors with meaningful level names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Transform data from numeric to factor</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Diabetes<span class="ot">&lt;-</span>Diabetes<span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Diabetes_binary=</span><span class="fu">factor</span>(Diabetes_binary,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"0"</span>,<span class="st">"1"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No Diabetes"</span>,<span class="st">"Prediabetes/Diabetes"</span>)),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">HighBP=</span><span class="fu">factor</span>(HighBP,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"0"</span>,<span class="st">"1"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No High BP"</span>,<span class="st">"High BP"</span>)),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">HighChol=</span><span class="fu">factor</span>(HighChol,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"0"</span>,<span class="st">"1"</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No High Cholesterol"</span>,<span class="st">"High Cholesterol"</span>)),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">CholCheck=</span><span class="fu">factor</span>(CholCheck,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"0"</span>,<span class="st">"1"</span>),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No Cholesterol Check In 5 Years"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Yes Cholesterol Check In 5 Years"</span>)),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Smoker=</span><span class="fu">factor</span>(Smoker,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Smoker"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Not A Smoker"</span>)),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">Stroke=</span><span class="fu">factor</span>(Stroke,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Diagnosed With Stroke"</span>,<span class="st">"No Stroke"</span>)),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">HeartDiseaseorAttack=</span><span class="fu">factor</span>(HeartDiseaseorAttack,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Coronary Heart Disease or Myocardial Infarction"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"No Heart Disease Evident"</span>)),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">PhysActivity=</span><span class="fu">factor</span>(PhysActivity,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Physical Activity in Past 30 Days"</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"No Physical Activity in Past 30 Days"</span>)),</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">Fruits=</span><span class="fu">factor</span>(Fruits,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Consume Fruit 1 Or More Times Per Day"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Does Not Consume Fruits Regularly"</span>)),</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>         <span class="at">Veggies=</span><span class="fu">factor</span>(Veggies,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Consume Vegetables 1 Or More Times Per Day"</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Does Not Consume Vegetables Regularly"</span>)),</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">HvyAlcoholConsump=</span><span class="fu">factor</span>(HvyAlcoholConsump,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Heavy Alcohol Consumer"</span>,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Not Heavy Alcohol Consumer"</span>)),</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>         <span class="at">AnyHealthcare=</span><span class="fu">factor</span>(AnyHealthcare,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Has Health Insurance"</span>,</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"No Health Insurance"</span>)),</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>         <span class="at">NoDocbcCost=</span><span class="fu">factor</span>(NoDocbcCost,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Missed Doctors Visit Due to Cost"</span>,</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"No Cost Barrier to Healthcare"</span>)),</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>         <span class="at">GenHlth=</span><span class="fu">factor</span>(GenHlth,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"2"</span>,<span class="st">"3"</span>,<span class="st">"4"</span>,<span class="st">"5"</span>),</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Excellent"</span>,<span class="st">"Very Good"</span>,<span class="st">"Good"</span>,<span class="st">"Fair"</span>,<span class="st">"Poor"</span>)),</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>         <span class="at">DiffWalk=</span><span class="fu">factor</span>(DiffWalk,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Difficulty With Walking or Stairs"</span>,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"No Difficulty With Walking or Stairs"</span>)),</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sex=</span><span class="fu">factor</span>(Sex,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"0"</span>,<span class="st">"1"</span>),</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Female"</span>,<span class="st">"Male"</span>)),</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>         <span class="at">Age=</span><span class="fu">factor</span>(Age,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"2"</span>,<span class="st">"3"</span>,<span class="st">"4"</span>,<span class="st">"5"</span>,<span class="st">"6"</span>,<span class="st">"7"</span>,<span class="st">"8"</span>,<span class="st">"9"</span>,<span class="st">"10"</span>,</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"11"</span>,<span class="st">"12"</span>,<span class="st">"13"</span>),</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"18-24"</span>,<span class="st">"25-29"</span>,<span class="st">"30-34"</span>,<span class="st">"35-39"</span>,<span class="st">"40-44"</span>,</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"45-49"</span>,<span class="st">"50-54"</span>,<span class="st">"55-59"</span>,<span class="st">"60-64"</span>,<span class="st">"65-69"</span>,</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"70-74"</span>,<span class="st">"75-79"</span>,<span class="st">"80 or older"</span>)),</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>         <span class="at">Education=</span><span class="fu">factor</span>(Education,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"2"</span>,<span class="st">"3"</span>,<span class="st">"4"</span>,<span class="st">"5"</span>,<span class="st">"6"</span>),</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Never Attended School Or Only Kindergarten"</span>,</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Grades 1-8"</span>,</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Grades 9-11"</span>,</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Grades 12 or GED"</span>,</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Some College or Technical School"</span>,</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Graduated College or Technical School"</span>)),</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>         <span class="at">Income=</span><span class="fu">factor</span>(Income,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"2"</span>,<span class="st">"3"</span>,<span class="st">"4"</span>,<span class="st">"5"</span>,<span class="st">"6"</span>,<span class="st">"7"</span>,<span class="st">"8"</span>),</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Less than $10,000"</span>,</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$10,000 to less than $15,000"</span>,</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$15,000 to less than $20,000"</span>,</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$20,000 to less than $25,000"</span>,</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$25,000 to less than $35,000"</span>,</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$35,000 to less than $50,000"</span>,</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$50,000 to less than $75,000"</span>,</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"$75,000 or more"</span>)),</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After transforming the data so that appropriate categorical variables are stored as such, it is important to check for missing values in the data as that can cause issues with modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check for na's in the data set Diabetes</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(Diabetes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>The result of FALSE shows there are no NA’s in the data set. This means this data is ready for the exploratory data analysis stage.</p>
</section>
<section id="summarizations" class="level2">
<h2 class="anchored" data-anchor-id="summarizations">Summarizations</h2>
<p>In this exploratory data analysis stage, we want to evaluate three variables that may be beneficial in predicting the diabetes status (i.e.&nbsp;the Diabetes_binary variable). To do this we can explore the variables in both uni variate and bivariate analyses.</p>
<section id="diabetes_binary" class="level4">
<h4 class="anchored" data-anchor-id="diabetes_binary">Diabetes_binary</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EDA_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
         No Diabetes Prediabetes/Diabetes 
              218334                35346 </code></pre>
</div>
</div>
<p>This bar plot shows the frequency of the respondents that had no diabetes diagnosis compared to those that had prediabetes or diabetes diagnoses. This confirms the original detail of the data that this is an unbalanced design. Specifically, we see that <span class="math inline">\(\frac{218334}{253680}\approx\)</span> 86.07%. This is the majority class rate that the accuracy of our models would need to do better than in order to be beneficial.</p>
<p>Three explanatory variables of interest to analyze are BMI, HvyAlcoholConsump, and Income. Research suggests that increased BMI is related to an increase in risk of diabetes (<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4457375/" class="uri">https://pmc.ncbi.nlm.nih.gov/articles/PMC4457375/</a>). Furthermore, it is possible that income relates to diabetes risk as healthy food is known to be expensive when compared to cheaper food. Alcohol consumption would also be a consideration as alcohol is high in sugar. Univariate analysis can be performed on these three variables to analyze their distributions. Bivariate analysis between each explanatory variable with the response variable is also useful to determine initial association based on statistical significance.</p>
</section>
<section id="bmi" class="level4">
<h4 class="anchored" data-anchor-id="bmi">BMI</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EDA_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The median of the BMI of the respondents is 27 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The range of the BMI of the respondents is 12 98 </code></pre>
</div>
</div>
<p>The univariate analysis of the BMI of the survey respondents shows that the distribution of BMIs is right skewed with a median of 27. According to the National Heart, Lung, and Blood Institute, a BMI over 24.9 is considered overweight (<a href="https://www.nhlbi.nih.gov/health/educational/lose_wt/risk.htm" class="uri">https://www.nhlbi.nih.gov/health/educational/lose_wt/risk.htm</a>). This analysis shows that a majority of the respondents were overweight based on BMI and earlier research was shown that high BMI is associated with increased risk in diabetes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EDA_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bivariate analysis of Diabetes_binary with BMI (with outliers removed) shows that the median BMI for respondents without diabetes is lower than median BMI for respondents with prediabetes/diabetes. This validates the assumption earlier based on the research that BMI may be a useful predictor of diabetes status.</p>
</section>
<section id="heavy-alcohol-consumption-hvyalcoholconsump" class="level4">
<h4 class="anchored" data-anchor-id="heavy-alcohol-consumption-hvyalcoholconsump">Heavy Alcohol Consumption (HvyAlcoholConsump)</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EDA_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Heavy Alcohol Consumer Not Heavy Alcohol Consumer 
                     14256                     239424 </code></pre>
</div>
</div>
<p>The univariate analysis of the HvyAlcoholConsump variable shows a bar plot similar to that of the Diabetes_binary response variable where there is a high frequency in one class and a low frequency in another. As discussed before, alcohol consumption might be associated with diabetes as alcohol contains high levels of sugar. Consider the proportion of respondents with prediabetes/diabetes and those that are heavy alcohol consumers is similar this variable should be considered as a potential explanatory variable.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                      HvyAlcoholConsump
Diabetes_binary        Heavy Alcohol Consumer Not Heavy Alcohol Consumer
  No Diabetes                           13424                     204910
  Prediabetes/Diabetes                    832                      34514</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(Diabetes_binary = Diabetes$Diabetes_binary, HvyAlcoholConsump = Diabetes$HvyAlcoholConsump)
X-squared = 825.12, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The bivariate analysis of Income and Diabetes_binary using a Chi-square test for independence shows statistically significance suggesting that the variables of Income and Diabetes_binary are not independent, and thus should be considered for use as a predictor. We performed this test on the contingency table shown above.</p>
</section>
<section id="income" class="level4">
<h4 class="anchored" data-anchor-id="income">Income</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EDA_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
           Less than $10,000 $10,000 to less than $15,000 
                        9811                        11783 
$15,000 to less than $20,000 $20,000 to less than $25,000 
                       15994                        20135 
$25,000 to less than $35,000 $35,000 to less than $50,000 
                       25883                        36470 
$50,000 to less than $75,000              $75,000 or more 
                       43219                        90385 </code></pre>
</div>
</div>
<p>The univariate analysis of the Income variable shows that the distribution is left skewed with the income of the respondents being relatively high in terms of the provided classes. As discussed prior, higher incomes are likely associated with less risk of diabetes since higher incomes provide access to healthy foods which are generally lower in sugar. Therefore, this variable may be a useful predictor as similarly to the other variables, the majority class of the variable is associated with the majority class of the diabetes variable which was no diabetes. It can be further analyzed with bivariate analysis whether income is statistically associated with diabetes status.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                      Income
Diabetes_binary        Less than $10,000 $10,000 to less than $15,000
  No Diabetes                       7428                         8697
  Prediabetes/Diabetes              2383                         3086
                      Income
Diabetes_binary        $15,000 to less than $20,000
  No Diabetes                                 12426
  Prediabetes/Diabetes                         3568
                      Income
Diabetes_binary        $20,000 to less than $25,000
  No Diabetes                                 16081
  Prediabetes/Diabetes                         4054
                      Income
Diabetes_binary        $25,000 to less than $35,000
  No Diabetes                                 21379
  Prediabetes/Diabetes                         4504
                      Income
Diabetes_binary        $35,000 to less than $50,000
  No Diabetes                                 31179
  Prediabetes/Diabetes                         5291
                      Income
Diabetes_binary        $50,000 to less than $75,000 $75,000 or more
  No Diabetes                                 37954           83190
  Prediabetes/Diabetes                         5265            7195</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(Diabetes_binary = Diabetes$Diabetes_binary, Income = Diabetes$Income)
X-squared = 7003.7, df = 7, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Using a Chi-square test for independence it appears statistically significant suggesting that the variables of Income and Diabetes_binary are not independent, and thus should be considered for use as a predictor. We performed this test on the contingency table shown above.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>